name: CI Conversor de Moedas

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: reports/results.xml